### ISSUE TITLE
npm install db-mysql - error on Ubuntu 11.04

### ISSUE THREAD

**Issue by wojciech-skowronek** [mariano/node-db-mysql#10]
Hi,

I'm trying to install your module on Ubuntu 11.04.

I have libmysqlclient-dev, and I have mysql_config in my PATH.

mysql_config --include gives me:

```
-I/usr/include/mysql
```

running

npm install db-mysql -g produce this error:

```
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /usr/share/node/lib/node_modules 
Checking for node prefix                 : ok /usr/share/node 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : yes 
'configure' finished successfully (2.851s)
Waf: Entering directory `/usr/share/node/lib/node_modules/db-mysql/build'
[ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
In file included from /usr/share/node/include/node/uv.h:40:0,
                 from /usr/share/node/include/node/node.h:25,
                 from ../lib/node-db/./binding.h:5,
                 from ../lib/node-db/binding.cc:2:
/usr/share/node/include/node/uv-unix.h:27:19: fatal error: ev/ev.h: No such file or directory
compilation terminated.
Waf: Leaving directory `/usr/share/node/lib/node_modules/db-mysql/build'
Build failed:  -> task failed (err #1): 
    {task: cxx binding.cc -> binding_1.o}
npm ERR! error installing db-mysql@0.5.9 Error: db-mysql@0.5.9 install: `node-waf configure build`
npm ERR! error installing db-mysql@0.5.9 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing db-mysql@0.5.9     at ChildProcess.<anonymous> (/usr/share/node/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing db-mysql@0.5.9     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing db-mysql@0.5.9     at ChildProcess.onexit (child_process.js:246:12)
npm ERR! db-mysql@0.5.9 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the db-mysql@0.5.9 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.38-8-server
npm ERR! command "node" "/usr/share/node/bin/npm" "install" "db-mysql" "-g"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/s/npm-debug.log
npm not ok
```

**Comment by wojciech-skowronek** [comment]
I check that also on my second machine with Ubuntu 10.10, and same issue occurs :(

**Comment by mariano** [comment]
It seems to me that you have issues with your local node.js installation, because of this line:

`/usr/share/node/include/node/uv-unix.h:27:19: fatal error: ev/ev.h: No such file or directory`

The compiler is basically telling you that a header file included within node does not exist. How did you install Node.js? I installed it on Ubuntu 11.04 by cloning from joyent's git repository, and building manually, and was able to install db-mysql with no issues

**Comment by wojciech-skowronek** [comment]
I downloaded node.0.4.8 from nodejs.org, and then call:

```
./configure --path=/usr/share/node
make
make install
```

In /usr/share/node/include/node I have ev.h file, but it's not in ev directory, maybe that's the problem? Anyway, I just copy ev directory from node-v0.4.8.tar.gz, and everything start working.

Thanks!
