### ISSUE TITLE
Library not loaded: libmysqlclient.18.dylib error on Snow Leopard

### ISSUE THREAD

**Issue by pgawle** [mariano/node-db-mysql#13]
What I have done: 
1. Install clean version of x64 Mysql
2. Add to my PATH variable 
   /usr/local/mysql/bin
3. Add 
   MYSQL_CONFIG=/usr/local/mysql/bin/mysql_config
4. Run npm install db-mysql and got 

``` ruby
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /Users/piotr/local/node/bin 
Checking for node prefix                 : ok /Users/piotr/local/node 
Checking for program mysql_config        : /usr/local/mysql/bin/mysql_config 
Checking for library mysqlclient_r       : yes 
'configure' finished successfully (0.557s)
Waf: Entering directory `/Users/piotr/Documents/Workspace/MieciuNode/devel/node_modules/db-mysql/build'
[ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
[ 2/11] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
[ 3/11] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
[ 4/11] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
[ 5/11] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
[ 6/11] cxx: src/connection.cc -> build/default/src/connection_1.o
[ 7/11] cxx: src/mysql.cc -> build/default/src/mysql_1.o
[ 8/11] cxx: src/query.cc -> build/default/src/query_1.o
[ 9/11] cxx: src/result.cc -> build/default/src/result_1.o
[10/11] cxx: src/mysql_bindings.cc -> build/default/src/mysql_bindings_1.o
[11/11] cxx_link: build/default/lib/node-db/binding_1.o build/default/lib/node-db/connection_1.o build/default/lib/node-db/exception_1.o build/default/lib/node-db/query_1.o build/default/lib/node-db/result_1.o build/default/src/connection_1.o build/default/src/mysql_1.o build/default/src/query_1.o build/default/src/result_1.o build/default/src/mysql_bindings_1.o -> build/default/mysql_bindings.node
Waf: Leaving directory `/Users/piotr/Documents/Workspace/MieciuNode/devel/node_modules/db-mysql/build'
'build' finished successfully (4.681s)
```

When running 
var mysql = require('db-mysql'); I'm getting

``` ruby
Error: dlopen(/Users/piotr/Documents/Workspace/MieciuNode/devel/node_modules/db-mysql/build/default/mysql_bindings.node, 1): Library not loaded: libmysqlclient.18.dylib
  Referenced from: /Users/piotr/Documents/Workspace/MieciuNode/devel/node_modules/db-mysql/build/default/mysql_bindings.node
  Reason: image not found
    at Object..node (module.js:416:11)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.<anonymous> (/Users/piotr/Documents/Workspace/MieciuNode/devel/node_modules/db-mysql/db-mysql.js:12:15)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
```

No idea why it is not working.  It seems I have everything installed correctly.  Node version 0.4.7

**Comment by mariano** [comment]
Wow ok this seems to be an issue with libraries in OSX, since I know other OSX users have not had any problems installing:

https://github.com/mariano/node-db-mysql/issues/2

Maybe @wfarr can share how he installed mysql for the libraries to work correctly?

@maxxxta: Could you also do me a favor and $ cd into the directory where db-mysql got installed (such as node_modules/db-mysql) and run the following (and then paste the output here):

```
$ rm -fr build/
$ node-waf configure build --verbose
```

**Comment by pgawle** [comment]
Thanks for response! Here is output

``` ruby
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /Users/piotr/local/node/bin 
Checking for node prefix                 : ok /Users/piotr/local/node 
Checking for program mysql_config        : /usr/local/mysql/bin/mysql_config 
Checking for library mysqlclient_r       : 15:46:06 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '../test.cpp', '-c', '-o', 'default/test_1.o']
15:46:07 runner system command -> ['/usr/bin/g++', 'default/test_1.o', '-o', '/Users/piotr/Documents/Workspace/MieciuNode/devel/node_modules/db-mysql/build/.conf_check_0/testbuild/default/testprog', '-L/usr/local/mysql/lib', '-lmysqlclient_r', '-lpthread']
yes 
'configure' finished successfully (1.033s)
Waf: Entering directory `/Users/piotr/Documents/Workspace/MieciuNode/devel/node_modules/db-mysql/build'
[ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
15:46:07 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../lib/node-db/binding.cc', '-c', '-o', 'default/lib/node-db/binding_1.o']
[ 2/11] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
15:46:07 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../lib/node-db/connection.cc', '-c', '-o', 'default/lib/node-db/connection_1.o']
[ 3/11] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
15:46:07 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../lib/node-db/exception.cc', '-c', '-o', 'default/lib/node-db/exception_1.o']
[ 4/11] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
15:46:08 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../lib/node-db/query.cc', '-c', '-o', 'default/lib/node-db/query_1.o']
[ 5/11] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
15:46:08 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../lib/node-db/result.cc', '-c', '-o', 'default/lib/node-db/result_1.o']
[ 6/11] cxx: src/connection.cc -> build/default/src/connection_1.o
15:46:09 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../src/connection.cc', '-c', '-o', 'default/src/connection_1.o']
[ 7/11] cxx: src/mysql.cc -> build/default/src/mysql_1.o
15:46:10 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../src/mysql.cc', '-c', '-o', 'default/src/mysql_1.o']
[ 8/11] cxx: src/query.cc -> build/default/src/query_1.o
15:46:10 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../src/query.cc', '-c', '-o', 'default/src/query_1.o']
[ 9/11] cxx: src/result.cc -> build/default/src/result_1.o
15:46:11 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../src/result.cc', '-c', '-o', 'default/src/result_1.o']
[10/11] cxx: src/mysql_bindings.cc -> build/default/src/mysql_bindings_1.o
15:46:11 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/local/mysql/include', '-fPIC', '-compatibility_version', '1', '-current_version', '1', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-DEV_MULTIPLICITY=0', '-Idefault/lib', '-I../lib', '-I/Users/piotr/local/node/include/node', '../src/mysql_bindings.cc', '-c', '-o', 'default/src/mysql_bindings_1.o']
[11/11] cxx_link: build/default/lib/node-db/binding_1.o build/default/lib/node-db/connection_1.o build/default/lib/node-db/exception_1.o build/default/lib/node-db/query_1.o build/default/lib/node-db/result_1.o build/default/src/connection_1.o build/default/src/mysql_1.o build/default/src/query_1.o build/default/src/result_1.o build/default/src/mysql_bindings_1.o -> build/default/mysql_bindings.node
15:46:11 runner system command -> ['/usr/bin/g++', 'default/lib/node-db/binding_1.o', 'default/lib/node-db/connection_1.o', 'default/lib/node-db/exception_1.o', 'default/lib/node-db/query_1.o', 'default/lib/node-db/result_1.o', 'default/src/connection_1.o', 'default/src/mysql_1.o', 'default/src/query_1.o', 'default/src/result_1.o', 'default/src/mysql_bindings_1.o', '-o', '/Users/piotr/Documents/Workspace/MieciuNode/devel/node_modules/db-mysql/build/default/mysql_bindings.node', '-L/usr/local/mysql/lib', '-lmysqlclient_r', '-lpthread', '-bundle', '-undefined', 'dynamic_lookup', '-L/Users/piotr/local/node/lib']
Waf: Leaving directory `/Users/piotr/Documents/Workspace/MieciuNode/devel/node_modules/db-mysql/build'
'build' finished successfully (4.851s)
```

**Comment by pgawle** [comment]
I have found solution. Here is the fix:

``` ruby
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/usr/local/mysql/lib/"
```

More detailed info on(check also comments): 
http://www.blog.bridgeutopiaweb.com/post/how-to-fix-mysql-load-issues-on-mac-os-x/

**Comment by mariano** [comment]
hehe that's the bad things about closed architectures: it makes it hard for us linux devs to test stuff without the ability of installing OSX in a virtual machine :)

Anyhow thanks for finding the fix, I'm battling with finishing up the db-oracle driver for initial release

**Comment by pkyeck** [comment]
maybe the fix should be added to the readme - would have save me some hours of searching.
