### ISSUE TITLE
Errors while installing from NPM on OS X

### ISSUE THREAD

**Issue by wfarr** [mariano/node-db-mysql#2]
The errors start here:

```
[ 8/11] cxx: src/query.cc -> build/default/src/query_1.o
In file included from ../src/connection.cc:2:
../src/./connection.h:5:25: error: mysql/mysql.h: No such file or directory
[ 9/11] cxx: src/result.cc -> build/default/src/result_1.o
In file included from ../src/result.cc:2:
../src/./result.h:5:25: error: mysql/mysql.h: No such file or directory
In file included from ../src/./connection.h:8,
                 from ../src/connection.cc:2:
../src/././result.h:16: error: expected ‘,’ or ‘...’ before ‘&’ token
```

Latest node and npm. Node and mysql installed via homebrew.

```
ree-1.8.7-2011.03 in wfarr/  
› ls /usr/local/Cellar/mysql/5.5.10/include 
decimal.h       my_compiler.h  my_net.h      mysql_embed.h    plugin_ftparser.h
errmsg.h        my_config.h    my_pthread.h  mysql_time.h     sql_common.h
keycache.h      my_dbug.h      my_sys.h      mysql_version.h  sql_state.h
m_ctype.h       my_dir.h       my_xml.h      mysqld_ername.h  sslopt-case.h
m_string.h      my_getopt.h    mysql/        mysqld_error.h   sslopt-longopts.h
my_alloc.h      my_global.h    mysql.h       plugin.h         sslopt-vars.h
my_attribute.h  my_list.h      mysql_com.h   plugin_audit.h   typelib.h

ree-1.8.7-2011.03 in wfarr/  
› ls /usr/local/Cellar/mysql/5.5.10/include/mysql
client_plugin.h  plugin_auth.h         service_my_snprintf.h       services.h
innodb_priv.h    plugin_auth_common.h  service_thd_alloc.h
plugin.h         plugin_ftparser.h     service_thd_wait.h
plugin_audit.h   psi/                  service_thread_scheduler.h
```

It looks like it's trying to find mysql.h inside the include/mysql directory instead of at the top-level.

**Comment by wfarr** [comment]
I was able to fix this problem by symlinking the mysql.h file into that directory. Now the compilation presents a new error:

```
ree-1.8.7-2011.03 in wfarr/  
› npm install -g db-mysql
> db-mysql@0.4.3 preinstall /usr/local/lib/node_modules/db-mysql
> node-waf configure

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.4.7 
Checking for library mysqlclient_r       : yes 
'configure' finished successfully (0.284s)

> db-mysql@0.4.3 install /usr/local/lib/node_modules/db-mysql
> node-waf build

Waf: Entering directory `/usr/local/lib/node_modules/db-mysql/build'
[ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
[ 2/11] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
[ 3/11] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
[ 4/11] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
[ 5/11] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
[ 6/11] cxx: src/connection.cc -> build/default/src/connection_1.o
[ 7/11] cxx: src/mysql.cc -> build/default/src/mysql_1.o
[ 8/11] cxx: src/query.cc -> build/default/src/query_1.o
[ 9/11] cxx: src/result.cc -> build/default/src/result_1.o
[10/11] cxx: src/mysql_bindings.cc -> build/default/src/mysql_bindings_1.o
../src/result.cc: In member function ‘virtual uint64_t* node_db_mysql::Result::columnLengths()’:
../src/result.cc:131: error: invalid conversion from ‘long unsigned int*’ to ‘uint64_t*’
../src/result.cc: In member function ‘virtual node_db_mysql::Result::Column* node_db_mysql::Result::column(uint16_t) const’:
../src/result.cc:146: warning: comparison is always false due to limited range of data type
Waf: Leaving directory `/usr/local/lib/node_modules/db-mysql/build'
Build failed:  -> task failed (err #1): 
    {task: cxx result.cc -> result_1.o}
npm ERR! error installing db-mysql@0.4.3 Error: db-mysql@0.4.3 install: `node-waf build`
npm ERR! error installing db-mysql@0.4.3 `sh "-c" "node-waf build"` failed with 1
npm ERR! error installing db-mysql@0.4.3     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing db-mysql@0.4.3     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing db-mysql@0.4.3     at ChildProcess.onexit (child_process.js:192:12)

> db-mysql@0.4.3 preuninstall /usr/local/lib/node_modules/db-mysql
> rm -rf build/*

npm ERR! db-mysql@0.4.3 install: `node-waf build`
npm ERR! `sh "-c" "node-waf build"` failed with 1
npm ERR! 
npm ERR! Failed at the db-mysql@0.4.3 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.7.4
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "db-mysql"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/wfarr/npm-debug.log
npm not ok
```

**Comment by mariano** [comment]
The compilation issue is fixed in the latest version, so run `$ npm install db-mysql` again and you should be good to go.

I'm interested in why you had to symlink the header. Do you have the mysql_config binary in the path? If so, what does this throw?

`$ mysql_config --include`

**Comment by mariano** [comment]
Actually nevermind my question. I found out while the mysql.h path was wrong.

You should now be able to install db-mysql without the symlink (but still with mysql_config in your path)

Enjoy!

**Comment by wfarr** [comment]
Yep, I can confirm this works now.
