### ISSUE TITLE
node-waf configure build fail : 'std::bad_typeid::~bad_typeid()'

### ISSUE THREAD

**Issue by FGRibreau** [mariano/node-db-mysql#20]
Hi, 

I got the following issue when doing a npm install db-mysql -g

```
'configure' finished successfully (0.526s)
Waf: Entering directory `/home/fundare/node-db-mysql/build'
[ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
[ 2/11] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
[ 3/11] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
[ 4/11] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
[ 5/11] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
[ 6/11] cxx: src/connection.cc -> build/default/src/connection_1.o
[ 7/11] cxx: src/mysql.cc -> build/default/src/mysql_1.o
[ 8/11] cxx: src/query.cc -> build/default/src/query_1.o
[ 9/11] cxx: src/result.cc -> build/default/src/result_1.o
[10/11] cxx: src/mysql_bindings.cc -> build/default/src/mysql_bindings_1.o
[11/11] cxx_link: build/default/lib/node-db/binding_1.o build/default/lib/node-db/connection_1.o build/default/lib/node-db/exception_1.o build/default/lib/node-db/query_1.o build/default/lib/node-db/result_1.o build/default/src/connection_1.o build/default/src/mysql_1.o build/default/src/query_1.o build/default/src/result_1.o build/default/src/mysql_bindings_1.o -> build/default/mysql_bindings.node
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.4.5/libstdc++.a(functexcept.o): relocation R_X86_64_32 against `std::bad_typeid::~bad_typeid()' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/libstdc++.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
Waf: Leaving directory `/home/fundare/node-db-mysql/build'
Build failed:  -> task failed (err #1): 
    {task: cxx_link binding_1.o,connection_1.o,exception_1.o,query_1.o,result_1.o,connection_1.o,mysql_1.o,query_1.o,result_1.o,mysql_bindings_1.o -> mysql_bindings.node}
```

I've tried to add the "-fPIC" by modifing wscript but it didn't seem to work at all. Any idea ?

PS: I got this issue on a Debian Squeeze. I worked on my mac.

**Comment by mariano** [comment]
This is clearly an issue with the way your libstdc++ library is statically compiled. Some people [recommend rebuilding libstdc++](http://gcc.gnu.org/ml/gcc-help/2005-05/msg00324.html).

Is your Debian Squeeze a brand new install? 32 bits or 64? I'm trying to see if I should take the effort to install a virtual machine to replicate.

**Comment by FGRibreau** [comment]
Yes, it's a 64bit Debian Squeeze brand new install but I don't think I got the knowledge to start rebuilding libstdc++  :s

**Comment by mariano** [comment]
I'm installing Debian Squeeze 64 bits on a VirtualMachine... It's taking some time on this laptop, so I'll let you know what I find

**Comment by mariano** [comment]
@FGRibreau: how did you install node in squeeze? Building from source, or through package manager?

**Comment by mariano** [comment]
I'm not seeing any issues whatsoever with a fresh new install of Debian Squeeze 64 bits. I first installed the needed packages:

``` bash
$ sudo apt-get install build-essential
$ sudo apt-get install nodejs
$ sudo apt-get install nodejs-dev
$ sudo apt-get install libmysqlclient-dev
```

Then I installed db-mysql (output pasted here)

```
$ npm install db-mysql

> db-mysql@0.6.7 install /home/mariano/node/node_modules/db-mysql
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : yes 
'configure' finished successfully (12.648s)
Waf: Entering directory `/home/mariano/node/node_modules/db-mysql/build'
[ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
[ 2/11] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
[ 3/11] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
[ 4/11] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
[ 5/11] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
[ 6/11] cxx: src/connection.cc -> build/default/src/connection_1.o
[ 7/11] cxx: src/mysql.cc -> build/default/src/mysql_1.o
[ 8/11] cxx: src/query.cc -> build/default/src/query_1.o
[ 9/11] cxx: src/result.cc -> build/default/src/result_1.o
[10/11] cxx: src/mysql_bindings.cc -> build/default/src/mysql_bindings_1.o
[11/11] cxx_link: build/default/lib/node-db/binding_1.o build/default/lib/node-db/connection_1.o build/default/lib/node-db/exception_1.o build/default/lib/node-db/query_1.o build/default/lib/node-db/result_1.o build/default/src/connection_1.o build/default/src/mysql_1.o build/default/src/query_1.o build/default/src/result_1.o build/default/src/mysql_bindings_1.o -> build/default/mysql_bindings.node
Waf: Leaving directory `/home/mariano/node/node_modules/db-mysql/build'
'build' finished successfully (3m29.274s)
db-mysql@0.6.7 ./node_modules/db-mysql
```

After which I tested a regular db-mysql connection and it worked.

**Comment by FGRibreau** [comment]
I hadn't nodejs-dev package installed but even after his installation, I always get this error. However I'm on Debian Squeeze 6 64Bit and it's a fresh install.

```
npm install db-mysql -g

> db-mysql@0.6.7 install /usr/local/lib/node_modules/db-mysql
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : yes 
'configure' finished successfully (0.545s)
Waf: Entering directory `/usr/local/lib/node_modules/db-mysql/build'
[ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
[ 2/11] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
[ 3/11] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
[ 4/11] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
[ 5/11] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
[ 6/11] cxx: src/connection.cc -> build/default/src/connection_1.o
[ 7/11] cxx: src/mysql.cc -> build/default/src/mysql_1.o
[ 8/11] cxx: src/query.cc -> build/default/src/query_1.o
[ 9/11] cxx: src/result.cc -> build/default/src/result_1.o
[10/11] cxx: src/mysql_bindings.cc -> build/default/src/mysql_bindings_1.o
[11/11] cxx_link: build/default/lib/node-db/binding_1.o build/default/lib/node-db/connection_1.o build/default/lib/node-db/exception_1.o build/default/lib/node-db/query_1.o build/default/lib/node-db/result_1.o build/default/src/connection_1.o build/default/src/mysql_1.o build/default/src/query_1.o build/default/src/result_1.o build/default/src/mysql_bindings_1.o -> build/default/mysql_bindings.node
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.4.5/libstdc++.a(functexcept.o): relocation R_X86_64_32 against `std::bad_typeid::~bad_typeid()' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/libstdc++.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
Waf: Leaving directory `/usr/local/lib/node_modules/db-mysql/build'
Build failed:  -> task failed (err #1): 
    {task: cxx_link binding_1.o,connection_1.o,exception_1.o,query_1.o,result_1.o,connection_1.o,mysql_1.o,query_1.o,result_1.o,mysql_bindings_1.o -> mysql_bindings.node}
npm ERR! error installing db-mysql@0.6.7 Error: db-mysql@0.6.7 install: `node-waf configure build`
npm ERR! error installing db-mysql@0.6.7 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing db-mysql@0.6.7     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing db-mysql@0.6.7     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing db-mysql@0.6.7     at ChildProcess.onexit (child_process.js:192:12)

> db-mysql@0.6.7 preuninstall /usr/local/lib/node_modules/db-mysql
> rm -rf build/*

npm ERR! db-mysql@0.6.7 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the db-mysql@0.6.7 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.32-5-amd64
npm ERR! command "node" "/usr/bin/npm" "install" "db-mysql" "-g"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok
```

**Comment by mariano** [comment]
You still haven't answered my previous question: how did you install node? Because if you installed from the package manager, without nodejs-dev you shouldn't have been able to even compile db-mysql.

I just tried a global install of db-mysql on my Squeeze and it also worked.

First thing I don't understand is that we both have a supposely fresh install of squeeze, yet your compilation looks completely different from mine. After an unsuccessful install of db-mysql, enter the db-mysql directory (/usr/local/lib/node_modules/db-mysql in your case because you are installing globally) and run:

``` bash
$ rm -fr build/ && node-waf configure build --verbose
```

Can you give me the output? For example mine is:

```
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : 10:19:40 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '../test.cpp', '-c', '-o', 'default/test_1.o']
10:19:40 runner system command -> ['/usr/bin/g++', 'default/test_1.o', '-o', '/home/mariano/node/node_modules/db-mysql/build/.conf_check_0/testbuild/default/testprog', '-rdynamic', '-L/usr/lib/mysql', '-lmysqlclient_r', '-Wl,-Bdynamic']
yes 
'configure' finished successfully (2.638s)
Waf: Entering directory `/home/mariano/node/node_modules/db-mysql/build'
[ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
10:19:41 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/binding.cc', '-c', '-o', 'default/lib/node-db/binding_1.o']
[ 2/11] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
10:19:44 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/connection.cc', '-c', '-o', 'default/lib/node-db/connection_1.o']
[ 3/11] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
10:19:45 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/exception.cc', '-c', '-o', 'default/lib/node-db/exception_1.o']
[ 4/11] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
10:19:45 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/query.cc', '-c', '-o', 'default/lib/node-db/query_1.o']
[ 5/11] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
10:19:51 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/result.cc', '-c', '-o', 'default/lib/node-db/result_1.o']
[ 6/11] cxx: src/connection.cc -> build/default/src/connection_1.o
10:19:51 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/connection.cc', '-c', '-o', 'default/src/connection_1.o']
[ 7/11] cxx: src/mysql.cc -> build/default/src/mysql_1.o
10:19:52 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/mysql.cc', '-c', '-o', 'default/src/mysql_1.o']
[ 8/11] cxx: src/query.cc -> build/default/src/query_1.o
10:19:54 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/query.cc', '-c', '-o', 'default/src/query_1.o']
[ 9/11] cxx: src/result.cc -> build/default/src/result_1.o
10:19:56 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/result.cc', '-c', '-o', 'default/src/result_1.o']
[10/11] cxx: src/mysql_bindings.cc -> build/default/src/mysql_bindings_1.o
10:19:56 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/mysql_bindings.cc', '-c', '-o', 'default/src/mysql_bindings_1.o']
[11/11] cxx_link: build/default/lib/node-db/binding_1.o build/default/lib/node-db/connection_1.o build/default/lib/node-db/exception_1.o build/default/lib/node-db/query_1.o build/default/lib/node-db/result_1.o build/default/src/connection_1.o build/default/src/mysql_1.o build/default/src/query_1.o build/default/src/result_1.o build/default/src/mysql_bindings_1.o -> build/default/mysql_bindings.node
10:19:58 runner system command -> ['/usr/bin/g++', 'default/lib/node-db/binding_1.o', 'default/lib/node-db/connection_1.o', 'default/lib/node-db/exception_1.o', 'default/lib/node-db/query_1.o', 'default/lib/node-db/result_1.o', 'default/src/connection_1.o', 'default/src/mysql_1.o', 'default/src/query_1.o', 'default/src/result_1.o', 'default/src/mysql_bindings_1.o', '-o', '/home/mariano/node/node_modules/db-mysql/build/default/mysql_bindings.node', '-rdynamic', '-L/usr/lib/mysql', '-lmysqlclient_r', '-shared', '-L/usr/lib']
```

Which shows you that:
1. -fPIC is added automatically.
2. There's no need for static linking the libstdc++ library

**Comment by FGRibreau** [comment]
Oh sorry, I built node from source and I can't give you the output of

```
rm -fr build/ && node-waf configure build --verbose
```

since it doesn't compile.

I've cloned the db-mysql git repository (and his node-db submodule) and  

```
rm -fr build/ && node-waf configure build --verbose
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : 17:06:23 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '../test.cpp', '-c', '-o', 'default/test_1.o']
17:06:23 runner system command -> ['/usr/bin/g++', 'default/test_1.o', '-o', '/home/fundare/node-db-mysql/build/.conf_check_0/testbuild/default/testprog', '-rdynamic', '-L/usr/lib/mysql', '-lmysqlclient_r', '-Wl,-Bdynamic']
yes 
'configure' finished successfully (0.530s)
Waf: Entering directory `/home/fundare/node-db-mysql/build'
[ 1/11] cxx: lib/node-db/binding.cc -> build/default/lib/node-db/binding_1.o
17:06:23 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/binding.cc', '-c', '-o', 'default/lib/node-db/binding_1.o']
[ 2/11] cxx: lib/node-db/connection.cc -> build/default/lib/node-db/connection_1.o
17:06:25 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/connection.cc', '-c', '-o', 'default/lib/node-db/connection_1.o']
[ 3/11] cxx: lib/node-db/exception.cc -> build/default/lib/node-db/exception_1.o
17:06:25 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/exception.cc', '-c', '-o', 'default/lib/node-db/exception_1.o']
[ 4/11] cxx: lib/node-db/query.cc -> build/default/lib/node-db/query_1.o
17:06:25 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/query.cc', '-c', '-o', 'default/lib/node-db/query_1.o']
[ 5/11] cxx: lib/node-db/result.cc -> build/default/lib/node-db/result_1.o
17:06:28 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../lib/node-db/result.cc', '-c', '-o', 'default/lib/node-db/result_1.o']
[ 6/11] cxx: src/connection.cc -> build/default/src/connection_1.o
17:06:28 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/connection.cc', '-c', '-o', 'default/src/connection_1.o']
[ 7/11] cxx: src/mysql.cc -> build/default/src/mysql_1.o
17:06:29 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/mysql.cc', '-c', '-o', 'default/src/mysql_1.o']
[ 8/11] cxx: src/query.cc -> build/default/src/query_1.o
17:06:30 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/query.cc', '-c', '-o', 'default/src/query_1.o']
[ 9/11] cxx: src/result.cc -> build/default/src/result_1.o
17:06:31 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/result.cc', '-c', '-o', 'default/src/result_1.o']
[10/11] cxx: src/mysql_bindings.cc -> build/default/src/mysql_bindings_1.o
17:06:31 runner system command -> ['/usr/bin/g++', '-g', '-Wall', '-I/usr/include/mysql', '-fPIC', '-DPIC', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_GNU_SOURCE', '-Idefault/lib', '-I../lib', '-I/usr/include/nodejs', '../src/mysql_bindings.cc', '-c', '-o', 'default/src/mysql_bindings_1.o']
[11/11] cxx_link: build/default/lib/node-db/binding_1.o build/default/lib/node-db/connection_1.o build/default/lib/node-db/exception_1.o build/default/lib/node-db/query_1.o build/default/lib/node-db/result_1.o build/default/src/connection_1.o build/default/src/mysql_1.o build/default/src/query_1.o build/default/src/result_1.o build/default/src/mysql_bindings_1.o -> build/default/mysql_bindings.node
17:06:32 runner system command -> ['/usr/bin/g++', 'default/lib/node-db/binding_1.o', 'default/lib/node-db/connection_1.o', 'default/lib/node-db/exception_1.o', 'default/lib/node-db/query_1.o', 'default/lib/node-db/result_1.o', 'default/src/connection_1.o', 'default/src/mysql_1.o', 'default/src/query_1.o', 'default/src/result_1.o', 'default/src/mysql_bindings_1.o', '-o', '/home/fundare/node-db-mysql/build/default/mysql_bindings.node', '-rdynamic', '-L/usr/lib/mysql', '-lmysqlclient_r', '-shared', '-L/usr/lib']
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.4.5/libstdc++.a(functexcept.o): relocation R_X86_64_32 against `std::bad_typeid::~bad_typeid()' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.4.5/libstdc++.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
Waf: Leaving directory `/home/fundare/node-db-mysql/build'
Build failed:  -> task failed (err #1): 
    {task: cxx_link binding_1.o,connection_1.o,exception_1.o,query_1.o,result_1.o,connection_1.o,mysql_1.o,query_1.o,result_1.o,mysql_bindings_1.o -> mysql_bindings.node}
```
