### ISSUE TITLE
Error When installing on Ubuntu 11.04

### ISSUE THREAD

**Issue by adamhalasz** [mariano/node-db-mysql#26]
I´m installing with this:

```
adam@adam-Parallels-Virtual-Platform:~$ export MYSQL_CONFIG=/usr/bin/mysql_config
adam@adam-Parallels-Virtual-Platform:~$ npm install db-mysql
```

But I get these errors:

```
> db-mysql@0.6.7 install /home/adam/node_modules/db-mysql
> node-waf configure build

sh: node-waf: not found
npm ERR! error installing db-mysql@0.6.7 Error: db-mysql@0.6.7 install: `node-waf configure build`
npm ERR! error installing db-mysql@0.6.7 `sh "-c" "node-waf configure build"` failed with 127
npm ERR! error installing db-mysql@0.6.7     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing db-mysql@0.6.7     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing db-mysql@0.6.7     at ChildProcess.onexit (child_process.js:192:12)

> db-mysql@0.6.7 preuninstall /home/adam/node_modules/db-mysql
> rm -rf build/*

npm ERR! db-mysql@0.6.7 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 127
npm ERR! 
npm ERR! Failed at the db-mysql@0.6.7 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.38-10-generic
npm ERR! command "node" "/usr/bin/npm" "install" "db-mysql"
npm ERR! cwd /home/adam
npm ERR! node -v v0.4.9
npm ERR! npm -v 1.0.18
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/adam/npm-debug.log
npm not ok
```

Before I always got this error on Mac OS X because mysql_config was not there. But I´m sure that mysql_config is in /usr/bin/mysql_config because of this:

```
adam@adam-Parallels-Virtual-Platform:~$ which mysql_config
/usr/bin/mysql_config

```

Maybe `sh: node-waf: not found` is the problem because this is the first error, but I don´t really know what to do with this. :S

So what´s the problem?

**Comment by adamhalasz** [comment]
Hey, I fixed it. The problem was that node-waf was not installed, I don´t really understand why it isn´t as default. But installing the node-dev module helped.

`sudo apt-get install node-dev`
