### ISSUE TITLE
Checking for library mysqlclient_r: no such environment: default

### ISSUE THREAD

**Issue by ghost** [mariano/node-db-mysql#33]
```
npm install db-mysql

> db-mysql@0.6.7 install /home/levijm/projects/node/node_modules/db-mysql
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
Checking for program mysql_config        : /usr/bin/mysql_config 
Checking for library mysqlclient_r       : no such environment: default
Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 16, in <module>
    Scripting.prepare(t, os.getcwd(), VERSION, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 145, in prepare
    prepare_impl(t, cwd, ver, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 135, in prepare_impl
    main()
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 188, in main
    fun(ctx)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 241, in configure
    conf.sub_config([''])
  File "/usr/local/bin/../lib/node/wafadmin/Configure.py", line 221, in sub_config
    self.recurse(k, name='configure')
  File "/usr/local/bin/../lib/node/wafadmin/Utils.py", line 634, in recurse
    f(self)
  File "/home/levijm/projects/node/node_modules/db-mysql/wscript", line 38, in configure
    conf.check_cxx(lib="mysqlclient_r", errmsg="Missing libmysqlclient_r")
  File "/usr/local/bin/../lib/node/wafadmin/Tools/config_c.py", line 567, in check_cxx
    return self.check(*k, **kw)
  File "/usr/local/bin/../lib/node/wafadmin/Tools/config_c.py", line 444, in check
    ret = self.run_c_code(*k, **kw)
  File "/usr/local/bin/../lib/node/wafadmin/Tools/config_c.py", line 521, in run_c_code
    o = bld(features=kw['features'], source=test_f_name, target='testprog')
  File "/usr/local/bin/../lib/node/wafadmin/Build.py", line 343, in __call__
    return TaskGen.task_gen(*k, **kw)
  File "/usr/local/bin/../lib/node/wafadmin/TaskGen.py", line 118, in __init__
    self.env = self.bld.env.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
npm ERR! error installing db-mysql@0.6.7 Error: db-mysql@0.6.7 install: `node-waf configure build`
npm ERR! error installing db-mysql@0.6.7 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing db-mysql@0.6.7     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing db-mysql@0.6.7     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing db-mysql@0.6.7     at ChildProcess.onexit (child_process.js:192:12)

> db-mysql@0.6.7 preuninstall /home/levijm/projects/node/node_modules/db-mysql
> rm -rf build/*

npm ERR! db-mysql@0.6.7 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the db-mysql@0.6.7 install script.
npm ERR! This is most likely a problem with the db-mysql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-mysql
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.38-11-generic
npm ERR! command "node" "/usr/local/bin/npm" "install" "db-mysql"
npm ERR! cwd /home/levijm/projects/node
npm ERR! node -v v0.4.12
npm ERR! npm -v 1.0.90
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/levijm/projects/node/npm-debug.log
npm not ok
```

Running mysql_config --libs_r:

```
-Wl,-Bsymbolic-functions -rdynamic -L/usr/lib/mysql -lmysqlclient_r
```

What does `no such environment:` mean?  and `default`?

**Comment by ghost** [comment]
Turns out to be the same issue as https://github.com/mariano/node-db-mysql/issues/32.  Same OS but uname -r gives: 2.6.38-11-generic , not *-server.
