### ISSUE TITLE
Error: Uncaught, unspecified 'error' event. at [object Object].emit (events.js:50:15)

### ISSUE THREAD

**Issue by bbigras** [mariano/node-db-mysql#38]
I have a "Error: Uncaught, unspecified 'error' event." I think it happens when I'm about to commit. Is there anything I can do to have more debug output or something to hunt this bug down?

Code

```
console.log("COMMIT");
conn.query().execute("COMMIT;", function(error, rows) {
    if (error) {
        console.log("error", error);
    } else {
        console.log("ok");
    }
});
```

Log

```
COMMIT

events.js:50
        throw new Error("Uncaught, unspecified 'error' event.");
        ^
Error: Uncaught, unspecified 'error' event.
    at [object Object].emit (events.js:50:15)
```

**Comment by mariano** [comment]
Yup, this happens when the query produces an error, and it's because you don't have an event cather for the error event. The change I did so node-db works under node 0.4.x, 0.5.x and above is producing. As a temporary workaround, just attach a callback:

``` javascript
conn.query().on('error', function() {}).execute("COMMIT;", function(error, rows) {
    if (error) {
        console.log("error", error);
    } else {
        console.log("ok");
    }
});
```

I'll work on a fix for this.

**Comment by bbigras** [comment]
I have the same log output using

```
conn.query().on('error', function() {}).execute("COMMIT;", function(error, rows) {
```

Log

```
COMMIT

events.js:50
        throw new Error("Uncaught, unspecified 'error' event.");
              ^
Error: Uncaught, unspecified 'error' event.
    at [object Object].emit (events.js:50:15)
```

**Comment by mariano** [comment]
Fixed, try the new package http://nodejsdb.org/2011/11/node-db-drivers-updated-7/

**Comment by bbigras** [comment]
It works. Thanks!
