### ISSUE TITLE
Error: Unable to load shared library

### ISSUE THREAD

**Issue by timohofmeijer** [mariano/node-db-mysql#46]
I get the Following error when trying to run a simple example on OS X :
(Not sure if its my setup or a bug, forgive me)

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Unable to load shared library /Users/Timo/nodejstest/node_modules/db-mysql/build/Release/mysql_bindings.node
    at Object..node (module.js:463:11)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/Timo/nodejstest/node_modules/db-mysql/db-mysql.js:18:15)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)

**Comment by andreas-bergstrom** [comment]
This is the same bug as this: https://github.com/Sannis/node-mysql-libmysqlclient/issues/107

I also experience it, moving down version by version to find a working one now.

**Comment by thejh** [comment]
Heh, I have the same problem with my library (nacl) - it works on node v0.4.12, but not on node v0.6.x.

**Comment by Ralle** [comment]
I am getting the same problem on Lion.

**Comment by snowtorious** [comment]
I also had this problem when running Node 0.6.7 on OSX. Setting DYLD_LIBRARY_PATH to the mysql lib directory fixed it for me. In my case this was /usr/local/mysql/lib.

**Comment by neb642** [comment]
I have the same problem, using windows xp...

**Comment by pixelfreak** [comment]
Same problem on OSX. Setting DYLD_LIBRARY_PATH didn't work :(

**Comment by marnberg** [comment]
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/
works in OS X 10.6 and node 0.6.10

**Comment by caseybecking** [comment]
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/
Worked on 10.7.3

**Comment by ThiagoMiranda** [comment]
Hi. I'm having the same problem in Ubuntu. Does anybody knows how to solve it?

**Comment by caseybecking** [comment]
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/

That worked for me.
