### ISSUE TITLE
Starting Node Get mySql_Binding Errors

### ISSUE THREAD

**Issue by dusts66** [mariano/node-db-mysql#78]
Not sure where is start to fix this.  I assume that it can't find mySql Server.  I am running everything locally on my Mac(10.6.8).  MySql is installed in /usr/local/mysql.  I install the db-mysql in my local project folder.  Below is the error when I start up node:

module.js:477
  process.dlopen(filename, module.exports);
          ^
Error: Unable to load shared library /Users/dustindavidson/Sites/adsweb/node_modules/db-mysql/build/Release/mysql_bindings.node
    at Object..node (module.js:477:11)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/Users/dustindavidson/Sites/adsweb/node_modules/db-mysql/db-mysql.js:18:15)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)

**Comment by qraynaud** [comment]
I believe this is due to a malfunction during install. Please npm remove node-db-mysql and install it again. Be extra careful for ERR messages during install. If there are some, please repot theme here if you don't understand them. A common error is either compiler is missing or libmysql-dev files not installed first. Those are a dependency to get this module working. If you didn't remember installing them, then there you have your problem. Install mysql dev files.
